### ISSUE TITLE
invalid memory address or nil pointer dereference when MSK only accepts TLS

### ISSUE THREAD

**Issue by Thiago-Dantas** [statsbomb/prometheus-msk-discovery#1]
Apparently `BootstrapBrokerString` doesn't exist when the MSK cluster only accepts TLS.
[By the SDK docs](https://docs.aws.amazon.com/sdk-for-go/api/service/kafka/#GetBootstrapBrokersOutput) it should be in `BootstrapBrokerStringTls` but I don't know much Go to offer a pull request on this

**Comment by joshm91** [comment]
Thanks for the report @Thiago-Dantas. This should be fixed now.

**Comment by Thiago-Dantas** [comment]
You should probably add kafka:ListNodes as a required IAM permission on the README

**Comment by joshm91** [comment]
Ahh good catch, thanks!
