### ISSUE TITLE
I am not able to get the metrics when i add  prometheus msk discovery as a side car container in the ecs cluster.Please help me.

### ISSUE THREAD

**Issue by kalavathiy** [statsbomb/prometheus-msk-discovery#14]

**Comment by kalavathiy** [comment]
docker file 

FROM golang:1.15-alpine
WORKDIR /src
RUN apk --no-cache add git
COPY *.go go.mod go.sum ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/prometheus-msk-discovery .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=0 /bin/prometheus-msk-discovery /bin/
ENTRYPOINT ["prometheus-msk-discovery"]
CMD ["/bin/prometheus-msk-discovery", "-config.write-to", "config_out/msk_file_sd.yml"]

prometheus.yml file

scrape_configs:
  - job_name: 'msk'
    file_sd_configs:
      - files:
            - /prometheus/config_out/msk_file_sd.yml       
        refresh_interval: 10m
    metric_relabel_configs:
      - regex: task_arn
        action: labeldrop

added side car container using efs volume and mount point is /config_out

**Comment by joshm91** [comment]
Can you please post any log messages that the service is outputting?

**Comment by kalavathiy** [comment]
2022/08/09 04:23:17 Writing 1 discovered exporters to msk_file_sd.yml

ts=2022-08-09T04:07:15.616Z caller=main.go:796 level=warn msg="Received SIGTERM, exiting gracefully..."
ts=2022-08-09T04:07:15.616Z caller=main.go:819 level=info msg="Stopping scrape discovery manager..."

**Comment by joshm91** [comment]
I don't think this is a problem with the service, I think you're outputting the sd file to a different location. Your Dockerfile sets the working directory to `/src` and then you're setting `-config.write-to` to `config_out/msk_file_sd.yaml`. That means that on disk the file will be located at `/src/config_out/msk_file_sd.yaml` but your EFS mount is at `/config_out` instead.

**Comment by kalavathiy** [comment]
do i need to change the EFS point or docker file to get the output.

**Comment by joshm91** [comment]
Either one would work, or you could just specify the ECS `args` parameter to pass in the `-config.write-to` argument rather than embedding it in the Dockerfile.

**Comment by kalavathiy** [comment]
i dont understand can you please elaborate on this

**Comment by joshm91** [comment]
Try just modifying the line in your Dockerfile to:
`CMD ["/bin/prometheus-msk-discovery", "-config.write-to", "/config_out/msk_file_sd.yml"]`.

That should write to the EFS volume, as long as the EFS volume is mounted on `/config_out`.

**Comment by kalavathiy** [comment]
do you want me to modfiy the below line lik ethis
CMD ["/bin/prometheus-msk-discovery", "-config.write-to", "/config_out"]

**Comment by joshm91** [comment]
It would need to be `CMD ["/bin/prometheus-msk-discovery", "-config.write-to", "/config_out/msk_file_sd.yml"]`

**Comment by kalavathiy** [comment]
i tried and no error in log file but in the prometheus tragets are not displayed with msk metrics.

2022/08/09 13:57:15 Writing 1 discovered exporters to msk_file_sd.yml

ts=2022-08-09T13:42:16.378Z caller=main.go:930 level=info msg="Server is ready to receive web requests."

**Comment by joshm91** [comment]
Sorry but I'm not sure I can help you any further unfortunately, just make sure that your Prometheus server can correctly access the EFS share. If the service isn't outputting any errors and it's successfully writing to a file then it's just a matter of making sure Prometheus is loading that file.

**Comment by kalavathiy** [comment]
yes prometheus is not loading that file.

**Comment by kalavathiy** [comment]
scrape_configs:
- job_name: msk
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  metric_relabel_configs:
  - separator: ;
    regex: task_arn
    replacement: $1
    action: labeldrop
  file_sd_configs:
  - files:
    - /prometheus/config_out/msk_file_sd.yml
