### ISSUE TITLE
Filtering clusters by name

### ISSUE THREAD

**Issue by mikelorant** [statsbomb/prometheus-msk-discovery#5]
Would you consider adding the capability to provide a regex filter to allow the results to be filtered by name?

I would like to have our production Prometheus cluster only monitor MSK clusters that have "production" in their name, while our development cluster monitor all other clusters.

This could be implemented with a new argument "-filter" that takes a string that is a regular expression.

Using regular expressions would make it far more powerful than globbing and easily allow for negative matches.

**Comment by joshm91** [comment]
Hi Mike, thanks for the request! This is now implemented and should be available in the latest release.

**Comment by joshm91** [comment]
I just realised that we don't get automatic builds in Dockerhub anymore on the free account so I'll push the latest image later today. Sorry for any inconvenience!

**Comment by joshm91** [comment]
@mikelorant All pushed to Docker hub now 👍

**Comment by mikelorant** [comment]
All I can say is this is well above what I was expecting. I plan to have this implemented earlier next week so will provide feedback then. Thanks so much again.

**Comment by mikelorant** [comment]
Confirmed working. Thanks again.
